"""rename email verification table

Revision ID: 05459ac874d1
Revises: a68a25ef1805
Create Date: 2026-03-06 23:14:35.205536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05459ac874d1'
down_revision: Union[str, Sequence[str], None] = 'a68a25ef1805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_code_email'), 'email_verification_code', ['email'], unique=False)
    op.drop_index(op.f('ix_emailverificationcode_email'), table_name='emailverificationcode')
    op.drop_table('emailverificationcode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailverificationcode',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('emailverificationcode_pkey'))
    )
    op.create_index(op.f('ix_emailverificationcode_email'), 'emailverificationcode', ['email'], unique=False)
    op.drop_index(op.f('ix_email_verification_code_email'), table_name='email_verification_code')
    op.drop_table('email_verification_code')
    # ### end Alembic commands ###
