"""add email verification code table

Revision ID: a68a25ef1805
Revises: a1c4f7b9d2e3
Create Date: 2026-03-06 23:11:49.324869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a68a25ef1805'
down_revision: Union[str, Sequence[str], None] = 'a1c4f7b9d2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailverificationcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emailverificationcode_email'), 'emailverificationcode', ['email'], unique=False)
    op.drop_index(op.f('ix_favorite_note_link_note_id'), table_name='favorite_note_link')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_token_hash'), table_name='refresh_token')
    op.create_index(op.f('ix_refresh_token_token_hash'), 'refresh_token', ['token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_token_token_hash'), table_name='refresh_token')
    op.create_index(op.f('ix_refresh_token_token_hash'), 'refresh_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.create_index(op.f('ix_favorite_note_link_note_id'), 'favorite_note_link', ['note_id'], unique=False)
    op.drop_index(op.f('ix_emailverificationcode_email'), table_name='emailverificationcode')
    op.drop_table('emailverificationcode')
    # ### end Alembic commands ###
